export type NicheContent = {
  h1: string
  subtitle: string
  intro: string
  benefits: { title: string; desc: string }[]
  useCases: { title: string; desc: string }[]
  faq: { q: string; a: string }[]
  cta: string
}

export type Niche = {
  slug: string
  keyword: string
  keywordEn: string
  icon: string
  tr: NicheContent
  en: NicheContent
}

export const NICHES: Niche[] = [
  {
    slug: 'restoranlar',
    keyword: 'restoran sosyal medya yönetimi',
    keywordEn: 'restaurant social media management',
    icon: '🍽️',
    tr: {
      h1: 'Restoranlar İçin AI Sosyal Medya İçerik Üretici',
      subtitle: 'Menü tanıtımlarından etkinlik duyurularına — restoranınızın sosyal medyasını AI ile otomatikleştirin.',
      intro: 'Yemek fotoğraflarını çekiyorsunuz ama caption yazmakla vakit mi kaybediyorsunuz? ViralSpark, restoran ve kafeler için özel olarak optimize edilmiş içerik üretir. Menü güncellemeleri, sezonluk kampanyalar, müşteri yorumu paylaşımları, happy hour duyuruları — her biri Instagram, TikTok ve X için ayrı formatlarda.',
      benefits: [
        { title: 'Menü Odaklı İçerik', desc: 'Yemek adını yazın, AI görsel açıklama, fiyat vurgusu ve CTA içeren caption üretsin.' },
        { title: 'Sezonluk Kampanyalar', desc: 'Ramazan menüsünden yılbaşı özel menüsüne — mevsimsel içerikler saniyeler içinde.' },
        { title: 'Google Maps Entegrasyonu', desc: 'Konum etiketli, yerel SEO dostu hashtag önerileriyle müşterilerinizi kapınıza yönlendirin.' },
        { title: 'Çoklu Platform', desc: 'Aynı içeriği Instagram, TikTok, X ve Facebook için ayrı optimize edin.' },
      ],
      useCases: [
        { title: 'Günün Menüsü Paylaşımı', desc: 'Her gün farklı ton ve format ile günün menüsünü paylaşın.' },
        { title: 'Müşteri Yorumu Vurgusu', desc: 'Google/TripAdvisor yorumlarını görsel paylaşım içeriğine dönüştürün.' },
        { title: 'Etkinlik Duyurusu', desc: 'Canlı müzik, özel akşam yemeği, brunch — etkinliklerinizi duyurun.' },
        { title: 'Personel Tanıtımı', desc: 'Şefinizi, baristanızı, garsonunuzu tanıtan samimi içerikler.' },
      ],
      faq: [
        { q: 'Restoran için hangi platformlar en etkili?', a: 'Instagram ve TikTok yemek içeriği için en güçlü platformlar. ViralSpark her ikisi için optimize edilmiş içerik üretir.' },
        { q: 'Menü fotoğrafı olmadan içerik üretebilir miyim?', a: 'Evet, sadece yemek adı ve açıklamasıyla caption, hashtag ve hikaye içeriği üretebilirsiniz.' },
        { q: 'Türkçe yemek terimleri doğru yazılıyor mu?', a: 'Kesinlikle. AI Türkçe mutfak terminolojisine hakimdir — lahmacun, künefe, mantı gibi terimleri doğru kullanır.' },
        { q: 'Kaç şubem varsa hepsini yönetebilir miyim?', a: 'Pro planda sınırsız içerik üretebilir, her şube için farklı marka profili oluşturabilirsiniz.' },
      ],
      cta: 'Restoranınız için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Social Media Content Generator for Restaurants',
      subtitle: 'From menu highlights to event announcements — automate your restaurant\'s social media with AI.',
      intro: 'You take the food photos, but writing captions eats up your time? ViralSpark generates content specifically optimized for restaurants and cafés. Menu updates, seasonal promotions, customer review highlights, happy hour announcements — each formatted separately for Instagram, TikTok, and X.',
      benefits: [
        { title: 'Menu-Focused Content', desc: 'Type a dish name and AI generates a visual description, price highlight, and CTA caption.' },
        { title: 'Seasonal Campaigns', desc: 'From holiday specials to summer menus — seasonal content in seconds.' },
        { title: 'Local SEO Hashtags', desc: 'Location-tagged, locally optimized hashtag suggestions to drive foot traffic.' },
        { title: 'Multi-Platform', desc: 'Optimize the same content separately for Instagram, TikTok, X, and Facebook.' },
      ],
      useCases: [
        { title: 'Daily Menu Posts', desc: 'Share your daily menu with a different tone and format every day.' },
        { title: 'Review Highlights', desc: 'Turn Google/TripAdvisor reviews into shareable social content.' },
        { title: 'Event Announcements', desc: 'Live music, special dinners, brunch — announce your events effortlessly.' },
        { title: 'Staff Spotlights', desc: 'Introduce your chef, barista, or servers with engaging personal content.' },
      ],
      faq: [
        { q: 'Which platforms work best for restaurants?', a: 'Instagram and TikTok dominate food content. ViralSpark generates optimized content for both.' },
        { q: 'Can I generate content without food photos?', a: 'Yes, just enter the dish name and description to get captions, hashtags, and story content.' },
        { q: 'Does it support food-specific terminology?', a: 'Absolutely. The AI understands culinary terms across multiple cuisines and languages.' },
        { q: 'Can I manage multiple locations?', a: 'On the Pro plan, you get unlimited content generation and separate brand profiles for each location.' },
      ],
      cta: 'Generate free content for your restaurant',
    },
  },
  {
    slug: 'e-ticaret',
    keyword: 'e-ticaret sosyal medya içerik üretici',
    keywordEn: 'ecommerce social media content generator',
    icon: '🛒',
    tr: {
      h1: 'E-Ticaret Mağazaları İçin AI İçerik Üretici',
      subtitle: 'Ürün tanıtımlarından kampanya duyurularına — online mağazanızın sosyal medyasını AI ile güçlendirin.',
      intro: 'Yüzlerce ürün, düzinelerce kampanya, sürekli yeni içerik ihtiyacı. E-ticaret markaları için sosyal medya yönetimi tam zamanlı bir iş. ViralSpark, ürün açıklamalarını sosyal medya içeriğine çevirir — tek tıkla Instagram carousel caption, TikTok ürün tanıtımı, X kampanya duyurusu.',
      benefits: [
        { title: 'Ürün URL\'den İçerik', desc: 'Ürün sayfanızın linkini yapıştırın, AI ürün özelliklerini çekerek içerik üretsin.' },
        { title: 'Kampanya Duyuruları', desc: 'Black Friday, 11.11, yılsonu indirimleri — kampanya içeriklerinizi saniyede oluşturun.' },
        { title: 'Toplu Üretim', desc: 'Tek seferde 20+ ürün için içerik üretin, haftalık takvimi doldurun.' },
        { title: 'Dönüşüm Odaklı', desc: 'Her caption\'da CTA, fiyat vurgusu ve aciliyet hissi — satışa yönlendiren içerik.' },
      ],
      useCases: [
        { title: 'Yeni Ürün Lansmanı', desc: 'Ürün çıkışında tüm platformlar için lansman içeriği hazırlayın.' },
        { title: 'İndirim Duyurusu', desc: '%50 indirim, kargo bedava, son 24 saat — aciliyet yaratan kampanya postları.' },
        { title: 'Müşteri Yorumu Paylaşımı', desc: 'Olumlu müşteri yorumlarını sosyal kanıt içeriğine dönüştürün.' },
        { title: 'Sezonluk Koleksiyon', desc: 'İlkbahar/yaz, sonbahar/kış koleksiyonlarını tanıtan seri içerikler.' },
      ],
      faq: [
        { q: 'Shopify/Trendyol mağazamdan otomatik ürün çekebilir mi?', a: 'Ürün URL\'nizi yapıştırarak içerik üretebilirsiniz. Doğrudan API entegrasyonu yakında geliyor.' },
        { q: 'Toplu içerik üretimi mümkün mü?', a: 'Evet, Pro planda toplu üretim aracıyla tek seferde 20+ ürün için içerik üretebilirsiniz.' },
        { q: 'Hangi e-ticaret platformları destekleniyor?', a: 'URL-den-içerik özelliği tüm e-ticaret platformlarıyla çalışır — Shopify, WooCommerce, Trendyol, Hepsiburada.' },
        { q: 'İçerikler satış odaklı mı?', a: 'Evet, her içerik CTA, fiyat/indirim vurgusu ve aciliyet hissi içerecek şekilde optimize edilir.' },
      ],
      cta: 'Mağazanız için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for E-Commerce Stores',
      subtitle: 'From product launches to flash sales — power your online store\'s social media with AI.',
      intro: 'Hundreds of products, dozens of campaigns, constant need for fresh content. Social media management for e-commerce brands is a full-time job. ViralSpark turns product descriptions into social media content — one click for Instagram carousel captions, TikTok product showcases, X campaign announcements.',
      benefits: [
        { title: 'URL-to-Content', desc: 'Paste your product page link and AI extracts features to generate content.' },
        { title: 'Campaign Announcements', desc: 'Black Friday, flash sales, end-of-season — create campaign content in seconds.' },
        { title: 'Bulk Generation', desc: 'Generate content for 20+ products at once, fill your weekly calendar.' },
        { title: 'Conversion-Focused', desc: 'Every caption includes a CTA, price highlight, and urgency — content that drives sales.' },
      ],
      useCases: [
        { title: 'New Product Launch', desc: 'Prepare launch content for all platforms when a product drops.' },
        { title: 'Sale Announcements', desc: '50% off, free shipping, last 24 hours — urgency-driven campaign posts.' },
        { title: 'Customer Review Sharing', desc: 'Turn positive customer reviews into social proof content.' },
        { title: 'Seasonal Collections', desc: 'Create series content introducing spring/summer and fall/winter collections.' },
      ],
      faq: [
        { q: 'Can it pull products from my Shopify store?', a: 'You can paste any product URL to generate content. Direct API integration is coming soon.' },
        { q: 'Is bulk content generation possible?', a: 'Yes, on the Pro plan you can generate content for 20+ products at once.' },
        { q: 'Which e-commerce platforms are supported?', a: 'The URL-to-content feature works with all platforms — Shopify, WooCommerce, Amazon, Etsy.' },
        { q: 'Is the content sales-focused?', a: 'Yes, every piece of content is optimized with CTAs, price highlights, and urgency triggers.' },
      ],
      cta: 'Generate free content for your store',
    },
  },
  {
    slug: 'fitness-spor-salonlari',
    keyword: 'fitness spor salonu sosyal medya',
    keywordEn: 'gym fitness social media content',
    icon: '💪',
    tr: {
      h1: 'Fitness & Spor Salonları İçin AI İçerik Üretici',
      subtitle: 'Antrenman ipuçlarından üye başarı hikayelerine — spor salonunuzun sosyal medyasını AI ile büyütün.',
      intro: 'Spor salonları için sosyal medya, üye kazanımının en güçlü kanalı. Ama her gün yeni içerik üretmek zor. ViralSpark, fitness sektörüne özel içerik üretir — motivasyon postları, antrenman programı tanıtımları, beslenme ipuçları, üye dönüşüm hikayeleri.',
      benefits: [
        { title: 'Motivasyon İçerikleri', desc: 'Günlük motivasyon postları, alıntılar ve ilham veren hikayeler — üyelerinizi harekete geçirin.' },
        { title: 'Antrenman Programları', desc: 'Haftanın antrenmanı, evde egzersiz serileri, HIIT programları için içerik üretin.' },
        { title: 'Üye Dönüşüm Hikayeleri', desc: 'Before/after hikayeleri, üye başarıları — sosyal kanıt içerikleri oluşturun.' },
        { title: 'Kampanya & Promosyon', desc: 'Yeni yıl indirimi, yaz kampanyası, arkadaşını getir — üyelik kampanyalarınızı duyurun.' },
      ],
      useCases: [
        { title: 'Günlük Motivasyon', desc: 'Her gün farklı bir motivasyon postu paylaşarak etkileşimi artırın.' },
        { title: 'Haftalık Program Tanıtımı', desc: 'Grup dersleri, PT seansları ve yeni programları duyurun.' },
        { title: 'Beslenme İpuçları', desc: 'Protein tarifleri, diyet önerileri, supplement bilgileri paylaşın.' },
        { title: 'Eğitmen Tanıtımı', desc: 'PT\'lerinizi ve grup dersi eğitmenlerinizi tanıtan içerikler.' },
      ],
      faq: [
        { q: 'Fitness içerikleri bilimsel olarak doğru mu?', a: 'AI genel fitness bilgisi üretir. Özel beslenme ve sağlık tavsiyeleri için profesyonel danışmanlık önerilir.' },
        { q: 'Before/after içerikleri oluşturabilir miyim?', a: 'Evet, üye hikayesi detaylarını girin ve AI etkili bir dönüşüm hikayesi formatında içerik üretsin.' },
        { q: 'Hangi sosyal medya platformları fitness için en iyi?', a: 'Instagram Reels ve TikTok antrenman videoları için, Instagram feed motivasyon postları için idealdir.' },
        { q: 'Birden fazla şube için kullanabilir miyim?', a: 'Pro planda her şube için ayrı marka profili oluşturabilirsiniz.' },
      ],
      cta: 'Spor salonunuz için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Gyms & Fitness Studios',
      subtitle: 'From workout tips to member success stories — grow your gym\'s social media with AI.',
      intro: 'Social media is the strongest channel for gym member acquisition. But creating daily content is tough. ViralSpark generates fitness-specific content — motivation posts, workout program features, nutrition tips, member transformation stories.',
      benefits: [
        { title: 'Motivation Content', desc: 'Daily motivation posts, quotes, and inspiring stories to activate your members.' },
        { title: 'Workout Programs', desc: 'Create content for workout of the week, home exercise series, HIIT programs.' },
        { title: 'Transformation Stories', desc: 'Before/after stories, member achievements — create social proof content.' },
        { title: 'Campaigns & Promos', desc: 'New year discounts, summer campaigns, refer-a-friend — announce membership deals.' },
      ],
      useCases: [
        { title: 'Daily Motivation', desc: 'Share a different motivation post every day to boost engagement.' },
        { title: 'Weekly Program Features', desc: 'Announce group classes, PT sessions, and new programs.' },
        { title: 'Nutrition Tips', desc: 'Share protein recipes, diet tips, and supplement information.' },
        { title: 'Trainer Spotlights', desc: 'Introduce your PTs and group class instructors with engaging content.' },
      ],
      faq: [
        { q: 'Is the fitness content scientifically accurate?', a: 'AI generates general fitness knowledge. Professional consultation is recommended for specific nutrition and health advice.' },
        { q: 'Can I create before/after content?', a: 'Yes, enter member story details and AI generates content in an effective transformation story format.' },
        { q: 'Which platforms are best for fitness?', a: 'Instagram Reels and TikTok for workout videos, Instagram feed for motivation posts.' },
        { q: 'Can I use it for multiple locations?', a: 'On the Pro plan, you can create separate brand profiles for each location.' },
      ],
      cta: 'Generate free content for your gym',
    },
  },
  {
    slug: 'guzellik-kuafor',
    keyword: 'güzellik salonu kuaför sosyal medya',
    keywordEn: 'beauty salon hairdresser social media',
    icon: '💇',
    tr: {
      h1: 'Güzellik Salonları & Kuaförler İçin AI İçerik Üretici',
      subtitle: 'Saç modellerinden cilt bakımına — güzellik salonunuzun sosyal medyasını AI ile parlak hale getirin.',
      intro: 'Güzellik sektörü görselliğin her şey olduğu bir alan. Ama en güzel işlerin bile etkileyici caption\'lara ihtiyacı var. ViralSpark, kuaför ve güzellik salonları için saç modeli tanıtımı, cilt bakımı ipuçları, ürün önerileri, before/after paylaşımları üretir.',
      benefits: [
        { title: 'Before/After İçerikleri', desc: 'Saç dönüşümü, cilt bakımı sonuçları — görsel karşılaştırma postları için etkili caption\'lar.' },
        { title: 'Trend Takibi', desc: 'Sezonun trend saç renkleri, kesim modelleri, bakım rutinleri hakkında içerik üretin.' },
        { title: 'Ürün Tanıtımları', desc: 'Kullandığınız ürünleri tanıtan, güven veren profesyonel içerikler.' },
        { title: 'Randevu Yönlendirme', desc: 'Her içerikte randevu CTA\'sı — sosyal medyadan randevu dönüşümü artırın.' },
      ],
      useCases: [
        { title: 'Günün İşi Paylaşımı', desc: 'En iyi işlerinizi her gün paylaşarak portföyünüzü büyütün.' },
        { title: 'Bakım İpuçları', desc: 'Evde saç bakımı, cilt rutini, makyaj önerileri paylaşın.' },
        { title: 'Kampanya Duyurusu', desc: 'İndirimli paketler, yeni hizmetler, özel günler için kampanyalar.' },
        { title: 'Ekip Tanıtımı', desc: 'Stilistlerinizi ve uzmanlarınızı tanıtan kişisel içerikler.' },
      ],
      faq: [
        { q: 'Güzellik sektörü için en iyi platform hangisi?', a: 'Instagram görsel portföy için, TikTok dönüşüm videoları için idealdir. ViralSpark her ikisi için optimize üretir.' },
        { q: 'Before/after caption\'ları çok satışçı olmuyor mu?', a: 'AI doğal ve samimi ton kullanır. Sonuç odaklı ama zorlamayan içerikler üretir.' },
        { q: 'Ürün markalarını içerikte kullanabilir miyim?', a: 'Evet, kullandığınız ürün markalarını belirtin ve AI onları doğal şekilde içeriğe dahil etsin.' },
        { q: 'Birden fazla hizmet için ayrı içerik üretebilir miyim?', a: 'Evet — saç, cilt, makyaj, tırnak her biri için ayrı içerik üretebilirsiniz.' },
      ],
      cta: 'Salonunuz için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Beauty Salons & Hair Stylists',
      subtitle: 'From hairstyles to skincare — make your beauty salon\'s social media shine with AI.',
      intro: 'The beauty industry is all about visuals. But even the most stunning work needs compelling captions. ViralSpark generates hairstyle showcases, skincare tips, product recommendations, and before/after content for salons and stylists.',
      benefits: [
        { title: 'Before/After Content', desc: 'Hair transformations, skincare results — compelling captions for visual comparison posts.' },
        { title: 'Trend Coverage', desc: 'Create content about trending hair colors, cuts, and care routines.' },
        { title: 'Product Features', desc: 'Professional, trust-building content showcasing the products you use.' },
        { title: 'Appointment CTAs', desc: 'Every piece includes a booking CTA — drive social media to appointment conversions.' },
      ],
      useCases: [
        { title: 'Daily Work Showcase', desc: 'Share your best work daily to build your portfolio.' },
        { title: 'Care Tips', desc: 'Share at-home hair care, skincare routines, and makeup tips.' },
        { title: 'Campaign Announcements', desc: 'Discounted packages, new services, and special occasion promotions.' },
        { title: 'Team Introductions', desc: 'Introduce your stylists and specialists with personalized content.' },
      ],
      faq: [
        { q: 'Which platform is best for beauty businesses?', a: 'Instagram for visual portfolios, TikTok for transformation videos. ViralSpark optimizes for both.' },
        { q: 'Won\'t before/after captions sound too salesy?', a: 'AI uses natural, authentic tones — results-focused without being pushy.' },
        { q: 'Can I mention product brands in the content?', a: 'Yes, specify the brands you use and AI naturally incorporates them.' },
        { q: 'Can I generate content for different services?', a: 'Yes — hair, skin, makeup, nails — each gets tailored content.' },
      ],
      cta: 'Generate free content for your salon',
    },
  },
  {
    slug: 'emlakcilar',
    keyword: 'emlakçı gayrimenkul sosyal medya',
    keywordEn: 'real estate agent social media',
    icon: '🏠',
    tr: {
      h1: 'Emlakçılar & Gayrimenkul İçin AI İçerik Üretici',
      subtitle: 'İlan tanıtımlarından pazar analizlerine — gayrimenkul sosyal medyanızı AI ile güçlendirin.',
      intro: 'Gayrimenkul sektöründe sosyal medya, potansiyel alıcılarla buluşmanın en hızlı yolu. ViralSpark, emlak ilanı tanıtımları, bölge analizleri, yatırım ipuçları ve açık ev duyuruları için içerik üretir.',
      benefits: [
        { title: 'İlan Tanıtımları', desc: 'Emlak özelliklerini girin, AI satış odaklı caption ve hashtag üretsin.' },
        { title: 'Bölge Analizleri', desc: 'Mahalle tanıtımları, ulaşım avantajları, yaşam kalitesi içerikleri.' },
        { title: 'Yatırım İçerikleri', desc: 'Gayrimenkul yatırımı ipuçları, pazar trendleri, getiri analizleri.' },
        { title: 'Güven İnşası', desc: 'Profesyonel imaj oluşturan, uzmanlık sergileyen içerikler.' },
      ],
      useCases: [
        { title: 'Yeni İlan Duyurusu', desc: 'Portföyünüzdeki yeni mülkleri tüm platformlarda duyurun.' },
        { title: 'Sanal Tur Daveti', desc: 'Sanal tur ve açık ev etkinliklerini duyuran içerikler.' },
        { title: 'Satış Başarısı', desc: 'Satılan mülkler ve mutlu müşterilerle sosyal kanıt oluşturun.' },
        { title: 'Pazar Güncellemesi', desc: 'Bölgesel fiyat trendleri ve pazar analizlerini paylaşın.' },
      ],
      faq: [
        { q: 'Emlak ilanı URL\'sinden içerik üretebilir miyim?', a: 'Evet, ilan linkini yapıştırın ve AI mülk özelliklerini çekerek içerik üretsin.' },
        { q: 'Birden fazla ilan için toplu içerik üretebilir miyim?', a: 'Pro planda toplu üretim aracıyla tek seferde birden fazla ilan için içerik üretebilirsiniz.' },
        { q: 'İçerikler yasal uyumlu mu?', a: 'AI genel pazarlama içeriği üretir. Yasal gereklilikleri ve mevzuatı kendi bölgenize göre kontrol etmeniz önerilir.' },
        { q: 'Hangi platformlar emlak için en etkili?', a: 'Instagram görsel ilan tanıtımı, LinkedIn profesyonel ağ, Facebook yerel topluluklar için idealdir.' },
      ],
      cta: 'Emlak işiniz için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Real Estate Agents',
      subtitle: 'From listing promotions to market analysis — power your real estate social media with AI.',
      intro: 'In real estate, social media is the fastest way to connect with potential buyers. ViralSpark generates listing promotions, neighborhood analyses, investment tips, and open house announcements.',
      benefits: [
        { title: 'Listing Promotions', desc: 'Enter property details and AI generates sales-focused captions and hashtags.' },
        { title: 'Neighborhood Guides', desc: 'Area introductions, transportation advantages, quality of life content.' },
        { title: 'Investment Content', desc: 'Real estate investment tips, market trends, ROI analyses.' },
        { title: 'Trust Building', desc: 'Professional, expertise-showcasing content that builds your personal brand.' },
      ],
      useCases: [
        { title: 'New Listing Announcements', desc: 'Announce new properties across all platforms.' },
        { title: 'Virtual Tour Invitations', desc: 'Content promoting virtual tours and open house events.' },
        { title: 'Sold Success Stories', desc: 'Build social proof with sold properties and happy clients.' },
        { title: 'Market Updates', desc: 'Share regional price trends and market analyses.' },
      ],
      faq: [
        { q: 'Can I generate content from listing URLs?', a: 'Yes, paste the listing link and AI extracts property details to create content.' },
        { q: 'Can I bulk-generate for multiple listings?', a: 'On the Pro plan, generate content for multiple listings at once with the bulk tool.' },
        { q: 'Is the content legally compliant?', a: 'AI generates general marketing content. Check legal requirements for your specific region.' },
        { q: 'Which platforms are best for real estate?', a: 'Instagram for visual listings, LinkedIn for professional networking, Facebook for local communities.' },
      ],
      cta: 'Generate free content for your listings',
    },
  },
  {
    slug: 'ajanslar',
    keyword: 'sosyal medya ajansı içerik üretim aracı',
    keywordEn: 'social media agency content tool',
    icon: '🏢',
    tr: {
      h1: 'Sosyal Medya Ajansları İçin AI İçerik Üretici',
      subtitle: 'Birden fazla müşteri, farklı sektörler — ajansınızın içerik üretim kapasitesini 10x artırın.',
      intro: 'Ajans olarak onlarca müşteriyi aynı anda yönetiyorsunuz. Her müşteri farklı sektör, farklı ton, farklı platform. ViralSpark, ajansınızın içerik üretim süreçlerini hızlandırır — müşteri başına dakikalar yerine saniyeler.',
      benefits: [
        { title: '10x İçerik Kapasitesi', desc: 'Saatler süren brief-to-content sürecini saniyelere indirin.' },
        { title: 'Marka Profilleri', desc: 'Her müşteri için ayrı marka profili — ton, sektör, hedef kitle otomatik.' },
        { title: 'Toplu Üretim & Takvim', desc: 'Bir müşterinin haftalık/aylık içerik takvimini tek seferde doldurun.' },
        { title: 'Çoklu Platform', desc: 'Aynı brief\'ten Instagram, TikTok, X, LinkedIn için ayrı optimize edilmiş çıktılar.' },
      ],
      useCases: [
        { title: 'Müşteri Onboarding', desc: 'Yeni müşteri geldiğinde ilk hafta içeriklerini hemen üretin.' },
        { title: 'Aylık İçerik Takvimi', desc: 'Her müşteri için 30 günlük içerik planını otomatik oluşturun.' },
        { title: 'Kriz Anı İçeriği', desc: 'Acil durumlarda hızlıca uygun ton ve mesajla içerik üretin.' },
        { title: 'A/B Test Varyasyonları', desc: 'Aynı mesajın farklı versiyonlarını üretip test edin.' },
      ],
      faq: [
        { q: 'Kaç müşteri için kullanabilirim?', a: 'Pro planda sınırsız içerik üretimi ve 3 marka profili. Ajans planı yakında.' },
        { q: 'Ekip üyeleri aynı hesabı kullanabilir mi?', a: 'Şu an tek kullanıcılı. Ekip planı yol haritasında var.' },
        { q: 'Müşteriye özel ton ayarlanabilir mi?', a: 'Evet, marka profili oluşturarak her müşteri için sektör, ton ve hedef kitle tanımlayabilirsiniz.' },
        { q: 'API erişimi var mı?', a: 'API erişimi yakında gelecek — kendi iş akışlarınıza entegre edebileceksiniz.' },
      ],
      cta: 'Ajansınız için ücretsiz deneyin',
    },
    en: {
      h1: 'AI Content Generator for Social Media Agencies',
      subtitle: 'Multiple clients, different industries — 10x your agency\'s content production capacity.',
      intro: 'As an agency, you manage dozens of clients simultaneously. Each client has a different industry, tone, and platform. ViralSpark accelerates your content production — seconds per client instead of hours.',
      benefits: [
        { title: '10x Content Capacity', desc: 'Reduce hours-long brief-to-content processes to seconds.' },
        { title: 'Brand Profiles', desc: 'Separate brand profiles for each client — tone, industry, audience automated.' },
        { title: 'Bulk Generation & Calendar', desc: 'Fill a client\'s weekly/monthly content calendar in one session.' },
        { title: 'Multi-Platform', desc: 'From the same brief, get separately optimized outputs for Instagram, TikTok, X, LinkedIn.' },
      ],
      useCases: [
        { title: 'Client Onboarding', desc: 'Generate the first week of content immediately for new clients.' },
        { title: 'Monthly Content Calendar', desc: 'Auto-generate 30-day content plans for each client.' },
        { title: 'Crisis Content', desc: 'Quickly produce appropriately toned content for urgent situations.' },
        { title: 'A/B Test Variations', desc: 'Generate different versions of the same message for testing.' },
      ],
      faq: [
        { q: 'How many clients can I use it for?', a: 'Pro plan includes unlimited generation and 3 brand profiles. Agency plan coming soon.' },
        { q: 'Can team members share an account?', a: 'Currently single-user. Team plan is on the roadmap.' },
        { q: 'Can I set client-specific tones?', a: 'Yes, create brand profiles to define industry, tone, and target audience for each client.' },
        { q: 'Is API access available?', a: 'API access is coming soon — integrate into your own workflows.' },
      ],
      cta: 'Try free for your agency',
    },
  },
  {
    slug: 'freelancerlar',
    keyword: 'freelancer sosyal medya yöneticisi araç',
    keywordEn: 'freelance social media manager tool',
    icon: '💻',
    tr: {
      h1: 'Freelancer Sosyal Medya Yöneticileri İçin AI Asistanı',
      subtitle: 'Daha fazla müşteri, daha az zaman — freelance işinizi AI ile ölçeklendirin.',
      intro: 'Freelancer olarak her şeyi tek başınıza yapıyorsunuz — strateji, içerik üretimi, yayınlama, raporlama. ViralSpark, içerik üretim sürenizi %80 kısaltarak daha fazla müşteriye hizmet vermenizi sağlar.',
      benefits: [
        { title: 'Zaman Tasarrufu', desc: 'Müşteri başına içerik süresini saatlerden dakikalara indirin.' },
        { title: 'Tutarlı Kalite', desc: 'Yorgun olduğunuzda bile AI tutarlı, profesyonel içerik üretir.' },
        { title: 'Uygun Fiyat', desc: 'Ayda 3$ — bir kahveden ucuz, sınırsız içerik üretim asistanı.' },
        { title: 'Portföy Büyütme', desc: 'Daha hızlı iş çıkararak daha fazla müşteri alabilirsiniz.' },
      ],
      useCases: [
        { title: 'Hızlı İçerik Döngüsü', desc: 'Müşteriden brief alın, saniyeler içinde 3 varyasyon sunun.' },
        { title: 'Çoklu Müşteri Yönetimi', desc: 'Her müşteri için farklı ton ve stilde içerik üretin.' },
        { title: 'Teklif Hazırlama', desc: 'Potansiyel müşteriye örnek içerik göstererek ikna edin.' },
        { title: 'İçerik Bankası', desc: 'Haftalık içerikleri toplu üreterek zaman kazanın.' },
      ],
      faq: [
        { q: 'Müşterilerim için ticari olarak kullanabilir miyim?', a: 'Evet, oluşturulan tüm içerikler ticari kullanıma açıktır.' },
        { q: 'Müşterime özel marka tonu ayarlayabilir miyim?', a: 'Evet, marka profili özelliğiyle her müşteri için ayrı ton ve stil tanımlayabilirsiniz.' },
        { q: 'Freelancer için hangi plan uygun?', a: 'Başlangıç planı 1-3 müşteri için yeterli, 3+ müşteri için Pro planı önerilir.' },
        { q: 'İçerikleri düzenleyebilir miyim?', a: 'Tabii ki. AI\'ın ürettiği içeriği kopyalayıp istediğiniz gibi düzenleyebilirsiniz.' },
      ],
      cta: 'Freelance işinizi hızlandırın — ücretsiz başlayın',
    },
    en: {
      h1: 'AI Assistant for Freelance Social Media Managers',
      subtitle: 'More clients, less time — scale your freelance business with AI.',
      intro: 'As a freelancer, you do everything yourself — strategy, content creation, publishing, reporting. ViralSpark cuts your content creation time by 80%, letting you serve more clients.',
      benefits: [
        { title: 'Time Savings', desc: 'Reduce per-client content time from hours to minutes.' },
        { title: 'Consistent Quality', desc: 'Even when you\'re tired, AI delivers consistent, professional content.' },
        { title: 'Affordable', desc: '$3/month — cheaper than a coffee, unlimited content generation assistant.' },
        { title: 'Portfolio Growth', desc: 'Deliver work faster and take on more clients.' },
      ],
      useCases: [
        { title: 'Quick Content Cycles', desc: 'Get a brief from clients, present 3 variations in seconds.' },
        { title: 'Multi-Client Management', desc: 'Generate content in different tones and styles for each client.' },
        { title: 'Proposal Preparation', desc: 'Show sample content to convince potential clients.' },
        { title: 'Content Banking', desc: 'Bulk-generate weekly content to save time.' },
      ],
      faq: [
        { q: 'Can I use it commercially for my clients?', a: 'Yes, all generated content is cleared for commercial use.' },
        { q: 'Can I set a custom brand tone per client?', a: 'Yes, use the brand profile feature to define tone and style for each client.' },
        { q: 'Which plan is right for freelancers?', a: 'Starter plan covers 1-3 clients, Pro is recommended for 3+ clients.' },
        { q: 'Can I edit the generated content?', a: 'Absolutely. Copy the AI output and customize it however you like.' },
      ],
      cta: 'Speed up your freelance work — start free',
    },
  },
  {
    slug: 'influencerlar',
    keyword: 'influencer içerik üretim aracı',
    keywordEn: 'influencer content creation tool',
    icon: '⭐',
    tr: {
      h1: 'Influencer\'lar İçin AI İçerik Üretici',
      subtitle: 'Yaratıcılığınızı tüketmeden her gün fresh içerik — AI asistanınızla.',
      intro: 'Influencer olarak sürekli yeni içerik üretmek zorundasınız. Ama yaratıcılık blokajları gerçek. ViralSpark, fikir üretiminden caption yazımına, hashtag araştırmasından thread oluşturmaya kadar her adımda yanınızda.',
      benefits: [
        { title: 'Yaratıcılık Blokajı Çözümü', desc: 'Konu sıkıntısı çektiğinizde AI düzinelerce içerik fikri önerir.' },
        { title: 'Tutarlı Paylaşım Ritmi', desc: 'Her gün paylaşım yaparak algoritma performansınızı artırın.' },
        { title: 'Hashtag Araştırması', desc: 'Nişinize özel, trend ve hedefli hashtag kombinasyonları.' },
        { title: 'Çoklu Format', desc: 'Feed, Reels, Story, Thread — her format için ayrı optimize.' },
      ],
      useCases: [
        { title: 'Günlük İçerik Fikirleri', desc: 'Nişinizi yazın, AI haftalık içerik takvimi önersin.' },
        { title: 'Sponsorlu İçerik', desc: 'Marka iş birliği caption\'larını hızlıca oluşturun.' },
        { title: 'Engagement Postları', desc: 'Soru-cevap, anket, tartışma başlatan etkileşim postları.' },
        { title: 'Bio Optimizasyonu', desc: 'Instagram, TikTok, X bio\'nuzun SEO optimize versiyonunu alın.' },
      ],
      faq: [
        { q: 'AI içerik otantik görünür mü?', a: 'AI sizin tonunuzu ve stilinizi öğrenir. Marka profili ile kişisel sesinizi koruyabilirsiniz.' },
        { q: 'Sponsorlu içeriklerde kullanabilir miyim?', a: 'Evet, marka adı ve ürün detaylarını girerek sponsorlu içerik üretebilirsiniz.' },
        { q: 'Viral skor nedir?', a: 'AI her içerik için tahmini etkileşim potansiyelini 0-100 arası puanlar.' },
        { q: 'Hangi nişler destekleniyor?', a: 'Moda, güzellik, fitness, yemek, seyahat, teknoloji, eğitim, lifestyle — tüm nişler.' },
      ],
      cta: 'İçerik üretiminizi hızlandırın — ücretsiz başlayın',
    },
    en: {
      h1: 'AI Content Generator for Influencers',
      subtitle: 'Fresh content daily without burning out your creativity — powered by your AI assistant.',
      intro: 'As an influencer, you need to constantly produce new content. But creative blocks are real. ViralSpark supports you at every step — from idea generation to captions, hashtag research to thread creation.',
      benefits: [
        { title: 'Creative Block Solution', desc: 'When you\'re stuck, AI suggests dozens of content ideas.' },
        { title: 'Consistent Posting Rhythm', desc: 'Post daily to boost your algorithm performance.' },
        { title: 'Hashtag Research', desc: 'Niche-specific, trending, and targeted hashtag combinations.' },
        { title: 'Multi-Format', desc: 'Feed, Reels, Story, Thread — separately optimized for each format.' },
      ],
      useCases: [
        { title: 'Daily Content Ideas', desc: 'Enter your niche and AI suggests a weekly content calendar.' },
        { title: 'Sponsored Content', desc: 'Quickly create brand collaboration captions.' },
        { title: 'Engagement Posts', desc: 'Q&A, polls, discussion-starting engagement posts.' },
        { title: 'Bio Optimization', desc: 'Get SEO-optimized versions of your Instagram, TikTok, X bios.' },
      ],
      faq: [
        { q: 'Does AI content look authentic?', a: 'AI learns your tone and style. Use brand profiles to maintain your personal voice.' },
        { q: 'Can I use it for sponsored content?', a: 'Yes, enter brand names and product details to generate sponsored content.' },
        { q: 'What is the viral score?', a: 'AI scores each piece of content 0-100 for estimated engagement potential.' },
        { q: 'Which niches are supported?', a: 'Fashion, beauty, fitness, food, travel, tech, education, lifestyle — all niches.' },
      ],
      cta: 'Speed up your content creation — start free',
    },
  },
  {
    slug: 'kucuk-isletmeler',
    keyword: 'küçük işletme sosyal medya yönetimi',
    keywordEn: 'small business social media management',
    icon: '🏪',
    tr: {
      h1: 'Küçük İşletmeler İçin AI Sosyal Medya Yönetimi',
      subtitle: 'Bütçeniz kısıtlı, zamanınız az — AI ile profesyonel sosyal medya yönetimi.',
      intro: 'Küçük işletme olarak sosyal medya ajansına bütçeniz yok, kendiniz yapmaya zamanınız yok. ViralSpark, ayda sadece 3$ ile profesyonel kalitede içerik üretmenizi sağlar. Ajans kalitesi, freelancer bütçesi.',
      benefits: [
        { title: 'Ajans Kalitesinde İçerik', desc: 'Profesyonel sosyal medya ajansı kalitesinde içerikler, aylık 3$ ile.' },
        { title: 'Sıfır Öğrenme Eğrisi', desc: 'Konu yazın, platform seçin, üret — teknik bilgi gerektirmez.' },
        { title: '5 Dakikada Haftalık Plan', desc: 'Bir haftanın tüm içeriklerini 5 dakikada oluşturun.' },
        { title: 'Yerel SEO Desteği', desc: 'Bölgenize özel hashtag ve konum etiketleri ile yerel müşterilerinize ulaşın.' },
      ],
      useCases: [
        { title: 'Günlük Paylaşım', desc: 'İşletmenizin günlük aktivitelerini paylaşan içerikler.' },
        { title: 'Ürün/Hizmet Tanıtımı', desc: 'Sunduğunuz ürün ve hizmetleri tanıtan profesyonel postlar.' },
        { title: 'Müşteri İlişkileri', desc: 'Müşteri yorumlarına yanıt, teşekkür postları, topluluk oluşturma.' },
        { title: 'Özel Gün İçerikleri', desc: 'Bayramlar, yıl dönümleri, yerel etkinlikler için hazır içerikler.' },
      ],
      faq: [
        { q: 'Sosyal medya bilgim yok, kullanabilir miyim?', a: 'Kesinlikle. ViralSpark sıfır teknik bilgiyle kullanılabilir — konu yazın, üret butonuna basın.' },
        { q: 'Gerçekten ayda 3$ mı?', a: 'Evet, Başlangıç planı aylık 3$. Ücretsiz planda da günde 5 üretim hakkı var.' },
        { q: 'Hangi sektörler için uygun?', a: 'Restoran, market, eczane, oto yıkama, berber — her yerel işletme için uygun.' },
        { q: 'İçerikleri ne zaman paylaşmalıyım?', a: 'İçerik takvimi özelliğimiz en uygun paylaşım zamanlarını önerir.' },
      ],
      cta: 'İşletmeniz için ücretsiz başlayın',
    },
    en: {
      h1: 'AI Social Media Management for Small Businesses',
      subtitle: 'Limited budget, limited time — professional social media management with AI.',
      intro: 'As a small business, you can\'t afford an agency and don\'t have time to do it yourself. ViralSpark lets you create professional-quality content for just $3/month. Agency quality, freelancer budget.',
      benefits: [
        { title: 'Agency-Quality Content', desc: 'Professional social media agency quality content for $3/month.' },
        { title: 'Zero Learning Curve', desc: 'Type a topic, pick a platform, generate — no technical skills needed.' },
        { title: 'Weekly Plan in 5 Minutes', desc: 'Create an entire week of content in just 5 minutes.' },
        { title: 'Local SEO Support', desc: 'Reach local customers with region-specific hashtags and location tags.' },
      ],
      useCases: [
        { title: 'Daily Posts', desc: 'Share your business\'s daily activities with engaging content.' },
        { title: 'Product/Service Showcases', desc: 'Professional posts introducing your products and services.' },
        { title: 'Customer Relations', desc: 'Reply to reviews, thank-you posts, community building.' },
        { title: 'Special Occasion Content', desc: 'Ready-made content for holidays, anniversaries, and local events.' },
      ],
      faq: [
        { q: 'I don\'t know social media, can I use it?', a: 'Absolutely. ViralSpark requires zero technical knowledge — type a topic, press generate.' },
        { q: 'Is it really $3/month?', a: 'Yes, the Starter plan is $3/month. The free plan offers 5 daily generations.' },
        { q: 'Which industries is it suitable for?', a: 'Restaurants, shops, pharmacies, car washes, barbers — any local business.' },
        { q: 'When should I post the content?', a: 'Our content calendar feature suggests optimal posting times.' },
      ],
      cta: 'Start free for your business',
    },
  },
  {
    slug: 'egitim-kocluk',
    keyword: 'eğitim koçluk sosyal medya içerik',
    keywordEn: 'education coaching social media content',
    icon: '📚',
    tr: {
      h1: 'Eğitim & Koçluk Sektörü İçin AI İçerik Üretici',
      subtitle: 'Online kurslardan bireysel koçluğa — eğitim markanızı AI ile büyütün.',
      intro: 'Eğitimciler ve koçlar için sosyal medya, öğrenci/danışan kazanımının en güçlü kanalı. ViralSpark, eğitim ipuçları, başarı hikayeleri, kurs tanıtımları ve motivasyon içerikleri üretir.',
      benefits: [
        { title: 'Uzmanlık İçerikleri', desc: 'Alanınızda otorite kuran, bilgi paylaşan profesyonel postlar.' },
        { title: 'Kurs Tanıtımı', desc: 'Online kurs, workshop, webinar duyuruları için dönüşüm odaklı içerik.' },
        { title: 'Öğrenci Başarıları', desc: 'Öğrenci/danışan başarı hikayelerini paylaşarak sosyal kanıt oluşturun.' },
        { title: 'Carousel İçerikler', desc: 'Eğitici carousel postlar — bilgi infografikleri, adım adım rehberler.' },
      ],
      useCases: [
        { title: 'Günlük İpucu', desc: 'Alanınızla ilgili günlük mini bilgi paylaşımları.' },
        { title: 'Kurs Lansman', desc: 'Yeni kurs veya programınızı heyecan verici bir şekilde duyurun.' },
        { title: 'Q&A İçerikleri', desc: 'Sık sorulan soruları içerik haline getirerek etkileşimi artırın.' },
        { title: 'Motivasyon Serisi', desc: 'Haftalık motivasyon ve ilham veren sözler paylaşın.' },
      ],
      faq: [
        { q: 'Eğitim içerikleri için en iyi format ne?', a: 'Instagram carousel eğitici içerikler için, Reels/TikTok kısa ipuçları için, Thread derinlemesine bilgi için idealdir.' },
        { q: 'Kurs satış içeriği üretebilir miyim?', a: 'Evet, kurs detaylarını girin ve AI dönüşüm odaklı satış içeriği üretsin.' },
        { q: 'Birden fazla konuda içerik üretebilir miyim?', a: 'Evet, her üretimde farklı bir konu girebilirsiniz. Sınırlama yok.' },
        { q: 'LinkedIn için de kullanabilir miyim?', a: 'Evet, LinkedIn postları da destekleniyor — profesyonel ton ve formatta.' },
      ],
      cta: 'Eğitim markanız için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Education & Coaching',
      subtitle: 'From online courses to personal coaching — grow your education brand with AI.',
      intro: 'For educators and coaches, social media is the most powerful channel for student/client acquisition. ViralSpark generates educational tips, success stories, course promotions, and motivational content.',
      benefits: [
        { title: 'Expertise Content', desc: 'Professional posts that establish authority and share knowledge in your field.' },
        { title: 'Course Promotions', desc: 'Conversion-focused content for online courses, workshops, and webinar announcements.' },
        { title: 'Student Success Stories', desc: 'Build social proof by sharing student/client success stories.' },
        { title: 'Carousel Content', desc: 'Educational carousel posts — info graphics, step-by-step guides.' },
      ],
      useCases: [
        { title: 'Daily Tips', desc: 'Share daily mini knowledge bites from your field.' },
        { title: 'Course Launch', desc: 'Announce your new course or program with excitement.' },
        { title: 'Q&A Content', desc: 'Turn frequently asked questions into engaging content.' },
        { title: 'Motivation Series', desc: 'Share weekly motivation and inspiring quotes.' },
      ],
      faq: [
        { q: 'What\'s the best format for educational content?', a: 'Instagram carousels for educational content, Reels/TikTok for quick tips, Threads for in-depth knowledge.' },
        { q: 'Can I generate course sales content?', a: 'Yes, enter course details and AI generates conversion-focused sales content.' },
        { q: 'Can I generate content on multiple topics?', a: 'Yes, enter a different topic each time. No limitations.' },
        { q: 'Does it work for LinkedIn?', a: 'Yes, LinkedIn posts are supported — in professional tone and format.' },
      ],
      cta: 'Generate free content for your education brand',
    },
  },
  {
    slug: 'seyahat-turizm',
    keyword: 'seyahat turizm sosyal medya içerik',
    keywordEn: 'travel tourism social media content',
    icon: '✈️',
    tr: {
      h1: 'Seyahat & Turizm İçin AI İçerik Üretici',
      subtitle: 'Otel tanıtımlarından rota önerilerine — turizm işletmenizin sosyal medyasını AI ile zenginleştirin.',
      intro: 'Turizm sektörü hayalleri satıyor. İyi bir caption, bir fotoğrafı rezervasyona dönüştürebilir. ViralSpark, otel, tur, restoran, etkinlik tanıtımları için merak uyandıran, seyahat tutkusu aşılayan içerikler üretir.',
      benefits: [
        { title: 'Merak Uyandıran İçerik', desc: 'Destinasyon tanıtımları, gizli noktalar, yerel deneyimler — seyahat tutkusu aşılayan postlar.' },
        { title: 'Çok Dilli Destek', desc: 'Türkçe ve İngilizce içerik üretimi — uluslararası misafirlerinize ulaşın.' },
        { title: 'Sezonluk Kampanyalar', desc: 'Erken rezervasyon, bayram özel, yaz sezonu — kampanya içeriklerinizi hazırlayın.' },
        { title: 'UGC Tarzı', desc: 'Doğal, gezgin perspektifinden yazılmış otantik tonda içerikler.' },
      ],
      useCases: [
        { title: 'Destinasyon Tanıtımı', desc: 'Otelin/turun bulunduğu bölgeyi tanıtan çekici içerikler.' },
        { title: 'Misafir Deneyimi', desc: 'Misafir yorumları ve deneyimlerini içerik haline getirin.' },
        { title: 'Aktivite Önerileri', desc: 'Bölgedeki yapılacaklar listesi, restoran önerileri, gizli noktalar.' },
        { title: 'Erken Rezervasyon', desc: 'Erken rezervasyon kampanyalarını duyuran aciliyet içerikleri.' },
      ],
      faq: [
        { q: 'İngilizce içerik üretebilir miyim?', a: 'Evet, Türkçe ve İngilizce dahil 20+ dilde içerik üretebilirsiniz.' },
        { q: 'Otel fotoğrafı olmadan içerik üretebilir miyim?', a: 'Evet, otel/tur adı ve özelliklerini yazarak caption ve hashtag üretebilirsiniz.' },
        { q: 'Booking/TripAdvisor yorumlarını kullanabilir miyim?', a: 'Evet, olumlu yorumları girin ve AI bunları sosyal medya içeriğine dönüştürsün.' },
        { q: 'Hangi platformlar turizm için en iyi?', a: 'Instagram ve TikTok görsel destinasyon içeriği için, Pinterest seyahat ilhamı için idealdir.' },
      ],
      cta: 'Turizm işletmeniz için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Travel & Tourism',
      subtitle: 'From hotel showcases to route suggestions — enrich your tourism business\'s social media with AI.',
      intro: 'The tourism industry sells dreams. A great caption can turn a photo into a booking. ViralSpark generates curiosity-sparking, wanderlust-inspiring content for hotels, tours, restaurants, and events.',
      benefits: [
        { title: 'Curiosity-Sparking Content', desc: 'Destination showcases, hidden gems, local experiences — wanderlust-inspiring posts.' },
        { title: 'Multilingual Support', desc: 'Turkish and English content generation — reach international guests.' },
        { title: 'Seasonal Campaigns', desc: 'Early bird, holiday specials, summer season — prepare your campaign content.' },
        { title: 'UGC Style', desc: 'Natural, traveler-perspective content in an authentic tone.' },
      ],
      useCases: [
        { title: 'Destination Showcases', desc: 'Attractive content introducing the area around your hotel/tour.' },
        { title: 'Guest Experiences', desc: 'Turn guest reviews and experiences into social content.' },
        { title: 'Activity Suggestions', desc: 'Things to do, restaurant recommendations, hidden spots in the area.' },
        { title: 'Early Bird Deals', desc: 'Urgency-driven content announcing early booking campaigns.' },
      ],
      faq: [
        { q: 'Can I generate content in English?', a: 'Yes, generate content in 20+ languages including Turkish and English.' },
        { q: 'Can I create content without hotel photos?', a: 'Yes, enter hotel/tour name and features to get captions and hashtags.' },
        { q: 'Can I use Booking/TripAdvisor reviews?', a: 'Yes, enter positive reviews and AI converts them into social media content.' },
        { q: 'Which platforms are best for tourism?', a: 'Instagram and TikTok for visual destinations, Pinterest for travel inspiration.' },
      ],
      cta: 'Generate free content for your tourism business',
    },
  },
  {
    slug: 'saglik-klinik',
    keyword: 'sağlık klinik doktor sosyal medya',
    keywordEn: 'healthcare clinic doctor social media',
    icon: '🏥',
    tr: {
      h1: 'Sağlık Sektörü & Klinikler İçin AI İçerik Üretici',
      subtitle: 'Hasta bilgilendirmeden hizmet tanıtımına — kliniğinizin sosyal medyasını profesyonel ve güvenilir tutun.',
      intro: 'Sağlık sektöründe sosyal medya güven inşası demek. ViralSpark, hasta bilgilendirme postları, tedavi tanıtımları, sağlıklı yaşam ipuçları ve klinik tanıtım içerikleri üretir — profesyonel, güvenilir ve bilgilendirici tonda.',
      benefits: [
        { title: 'Güvenilir Ton', desc: 'Tıbbi terminolojiyi anlaşılır kılan, güven veren profesyonel içerik.' },
        { title: 'Hasta Bilgilendirme', desc: 'Hastalık önleme, tedavi süreçleri, bakım ipuçları hakkında eğitici postlar.' },
        { title: 'Hizmet Tanıtımı', desc: 'Klinik hizmetlerinizi tanıtan, randevu almaya yönlendiren içerikler.' },
        { title: 'Ekip Tanıtımı', desc: 'Doktor ve uzman kadronuzu tanıtarak hastalarla bağ kurun.' },
      ],
      useCases: [
        { title: 'Sağlık İpuçları', desc: 'Mevsimsel sağlık önerileri, önleyici bakım bilgileri paylaşın.' },
        { title: 'Tedavi Tanıtımı', desc: 'Sunduğunuz tedavi ve prosedürleri anlaşılır dille tanıtın.' },
        { title: 'Hasta Başarı Hikayesi', desc: 'İzinli hasta deneyimlerini paylaşarak güven oluşturun.' },
        { title: 'Özel Gün İçerikleri', desc: 'Dünya Sağlık Günü, Kalp Haftası gibi temalı içerikler.' },
      ],
      faq: [
        { q: 'Sağlık içerikleri tıbbi olarak doğru mu?', a: 'AI genel sağlık bilgisi üretir. Klinik bilgilerinizi ve uzman görüşünüzü ekleyerek özelleştirin.' },
        { q: 'Hasta mahremiyeti korunuyor mu?', a: 'AI hiçbir gerçek hasta bilgisi kullanmaz. İçerikler genel sağlık konularında üretilir.' },
        { q: 'Reklamcılık kurallarına uygun mu?', a: 'AI genel bilgilendirme tonu kullanır. Sağlık reklamcılığı mevzuatını kendi bölgenize göre kontrol edin.' },
        { q: 'Diş klinikleri için de uygun mu?', a: 'Evet — diş, göz, estetik, fizyoterapi ve tüm sağlık alanları için uygundur.' },
      ],
      cta: 'Kliniğiniz için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Healthcare & Clinics',
      subtitle: 'From patient education to service promotion — keep your clinic\'s social media professional and trustworthy.',
      intro: 'In healthcare, social media means trust building. ViralSpark generates patient education posts, treatment showcases, healthy living tips, and clinic promotion content — professional, trustworthy, and informative.',
      benefits: [
        { title: 'Trustworthy Tone', desc: 'Professional content that makes medical terminology accessible and builds trust.' },
        { title: 'Patient Education', desc: 'Educational posts about disease prevention, treatment processes, and care tips.' },
        { title: 'Service Promotion', desc: 'Content showcasing your clinic services and driving appointment bookings.' },
        { title: 'Team Introductions', desc: 'Introduce your doctors and specialists to build patient connections.' },
      ],
      useCases: [
        { title: 'Health Tips', desc: 'Share seasonal health advice and preventive care information.' },
        { title: 'Treatment Showcases', desc: 'Introduce treatments and procedures in accessible language.' },
        { title: 'Patient Success Stories', desc: 'Build trust by sharing permitted patient experiences.' },
        { title: 'Awareness Days', desc: 'World Health Day, Heart Week, and other themed content.' },
      ],
      faq: [
        { q: 'Is the health content medically accurate?', a: 'AI generates general health information. Customize with your clinical expertise and professional opinions.' },
        { q: 'Is patient privacy protected?', a: 'AI doesn\'t use any real patient data. Content is generated on general health topics.' },
        { q: 'Is it compliant with advertising regulations?', a: 'AI uses a general informational tone. Check healthcare advertising regulations for your region.' },
        { q: 'Is it suitable for dental clinics?', a: 'Yes — dental, eye care, aesthetics, physiotherapy, and all healthcare fields.' },
      ],
      cta: 'Generate free content for your clinic',
    },
  },
  {
    slug: 'hukuk-avukatlar',
    keyword: 'avukat hukuk bürosu sosyal medya',
    keywordEn: 'lawyer law firm social media',
    icon: '⚖️',
    tr: {
      h1: 'Avukatlar & Hukuk Büroları İçin AI İçerik Üretici',
      subtitle: 'Hukuki bilgilendirmeden büro tanıtımına — profesyonel ve güvenilir hukuk içerikleri üretin.',
      intro: 'Hukuk sektöründe sosyal medya, potansiyel müvekkil kazanımı ve marka bilinirliği için kritik. ViralSpark, hukuki bilgilendirme postları, uzmanlık alanı tanıtımları, başarı hikayeleri ve büro tanıtım içerikleri üretir.',
      benefits: [
        { title: 'Otorite İnşası', desc: 'Uzmanlık alanınızda bilgi paylaşarak sektörde otorite konumuna gelin.' },
        { title: 'Hukuki Bilgilendirme', desc: 'Karmaşık hukuki konuları anlaşılır dille vatandaşa aktaran postlar.' },
        { title: 'Profesyonel İmaj', desc: 'Ciddi, güvenilir ve profesyonel tonda içerikler.' },
        { title: 'Danışan Çekimi', desc: 'Her içerikte randevu/danışma CTA\'sı ile danışan dönüşümünü artırın.' },
      ],
      useCases: [
        { title: 'Hukuki Bilgi Paylaşımı', desc: 'Sık sorulan hukuki soruları kısa ve anlaşılır postlarla yanıtlayın.' },
        { title: 'Mevzuat Güncellemeleri', desc: 'Yeni yasalar ve düzenlemeler hakkında bilgilendirici içerikler.' },
        { title: 'Uzmanlık Tanıtımı', desc: 'İcra, ceza, ticaret, aile hukuku gibi uzmanlıklarınızı tanıtın.' },
        { title: 'Büro Tanıtımı', desc: 'Ekibinizi, başarılarınızı ve değerlerinizi tanıtan kurumsal içerikler.' },
      ],
      faq: [
        { q: 'Hukuki içerikler doğru mu?', a: 'AI genel hukuk bilgisi üretir. Kesin hukuki tavsiye için içeriği mutlaka kendi uzmanlığınızla kontrol edin.' },
        { q: 'Avukatlar sosyal medya kullanabilir mi?', a: 'Evet, baro kurallarına uygun şekilde bilgilendirici içerik paylaşımı serbesttir.' },
        { q: 'LinkedIn için de uygun mu?', a: 'Evet, LinkedIn hukuk profesyonelleri için en güçlü platformdur. ViralSpark LinkedIn postları da üretir.' },
        { q: 'Müvekkil gizliliği korunuyor mu?', a: 'AI hiçbir gerçek müvekkil bilgisi kullanmaz. İçerikler genel hukuki konularda üretilir.' },
      ],
      cta: 'Büronuz için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Lawyers & Law Firms',
      subtitle: 'From legal education to firm branding — generate professional, trustworthy legal content.',
      intro: 'In the legal sector, social media is critical for client acquisition and brand awareness. ViralSpark generates legal education posts, expertise showcases, success stories, and firm branding content.',
      benefits: [
        { title: 'Authority Building', desc: 'Share expertise to establish yourself as an authority in your field.' },
        { title: 'Legal Education', desc: 'Posts that make complex legal topics accessible to the public.' },
        { title: 'Professional Image', desc: 'Serious, trustworthy, and professional-toned content.' },
        { title: 'Client Acquisition', desc: 'Every piece includes consultation CTAs to boost client conversion.' },
      ],
      useCases: [
        { title: 'Legal FAQs', desc: 'Answer common legal questions in short, accessible posts.' },
        { title: 'Regulation Updates', desc: 'Informative content about new laws and regulations.' },
        { title: 'Expertise Showcases', desc: 'Introduce your specializations in criminal, commercial, family law, etc.' },
        { title: 'Firm Branding', desc: 'Corporate content showcasing your team, achievements, and values.' },
      ],
      faq: [
        { q: 'Is the legal content accurate?', a: 'AI generates general legal knowledge. Always verify with your own expertise for specific legal advice.' },
        { q: 'Can lawyers use social media?', a: 'Yes, sharing informative content in compliance with bar rules is permitted.' },
        { q: 'Is it suitable for LinkedIn?', a: 'Yes, LinkedIn is the strongest platform for legal professionals. ViralSpark generates LinkedIn posts.' },
        { q: 'Is client confidentiality protected?', a: 'AI doesn\'t use any real client information. Content is generated on general legal topics.' },
      ],
      cta: 'Generate free content for your firm',
    },
  },
  {
    slug: 'muzik-sanatcilar',
    keyword: 'müzisyen sanatçı sosyal medya',
    keywordEn: 'musician artist social media',
    icon: '🎵',
    tr: {
      h1: 'Müzisyenler & Sanatçılar İçin AI İçerik Üretici',
      subtitle: 'Yeni şarkı tanıtımından konser duyurularına — müzik kariyerinizi sosyal medyada AI ile büyütün.',
      intro: 'Müzik yapıyorsunuz ama sosyal medya yönetimi başlı başına bir iş. ViralSpark, şarkı tanıtımları, konser duyuruları, sahne arkası hikayeleri ve fan etkileşim içerikleri üretir.',
      benefits: [
        { title: 'Şarkı Tanıtımı', desc: 'Yeni single, albüm, EP lansmanlarınız için heyecan yaratan içerikler.' },
        { title: 'Fan Etkileşimi', desc: 'Q&A, anket, sahne arkası — hayranlarınızla bağ kuran postlar.' },
        { title: 'Konser Duyurusu', desc: 'Etkinlik detayları, bilet linkleri — konserlerinizi etkili şekilde duyurun.' },
        { title: 'Platform Çeşitliliği', desc: 'Instagram, TikTok, X, YouTube Community — her platform için ayrı içerik.' },
      ],
      useCases: [
        { title: 'Release Geri Sayımı', desc: 'Yeni şarkı çıkışına geri sayım serisi oluşturun.' },
        { title: 'Sahne Arkası', desc: 'Stüdyo çalışması, prova, tur hayatından anlar paylaşın.' },
        { title: 'Cover/Remix Tanıtımı', desc: 'Cover veya remix çalışmalarınızı tanıtın.' },
        { title: 'Streaming Yönlendirme', desc: 'Spotify, Apple Music, YouTube Music linklerinize trafik çekin.' },
      ],
      faq: [
        { q: 'Müzik türüne özel içerik üretebilir miyim?', a: 'Evet, pop, rock, rap, elektronik, klasik — müzik türünüzü belirtin ve AI uygun tonda içerik üretsin.' },
        { q: 'Şarkı sözü yazabilir mi?', a: 'ViralSpark sosyal medya içeriği üretir. Şarkı sözü yazımı için farklı araçlar önerilir.' },
        { q: 'Bilet satış linki ekleyebilir miyim?', a: 'Tabii ki. AI caption\'a bilet satış CTA\'sı ve link yönlendirmesi ekler.' },
        { q: 'Bağımsız sanatçılar için uygun mu?', a: 'Kesinlikle. Bağımsız müzisyenler için en uygun fiyatlı profesyonel içerik aracı.' },
      ],
      cta: 'Müzik kariyeriniz için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Musicians & Artists',
      subtitle: 'From new releases to tour announcements — grow your music career on social media with AI.',
      intro: 'You make music, but managing social media is a full-time job itself. ViralSpark generates release promos, concert announcements, behind-the-scenes stories, and fan engagement content.',
      benefits: [
        { title: 'Release Promotions', desc: 'Hype-building content for new singles, albums, and EP launches.' },
        { title: 'Fan Engagement', desc: 'Q&A, polls, behind-the-scenes — posts that connect with fans.' },
        { title: 'Show Announcements', desc: 'Event details, ticket links — effectively promote your shows.' },
        { title: 'Platform Variety', desc: 'Instagram, TikTok, X, YouTube Community — separate content for each.' },
      ],
      useCases: [
        { title: 'Release Countdown', desc: 'Create a countdown series for your new release.' },
        { title: 'Behind the Scenes', desc: 'Share moments from studio sessions, rehearsals, and tour life.' },
        { title: 'Cover/Remix Promos', desc: 'Promote your cover and remix projects.' },
        { title: 'Streaming Drives', desc: 'Drive traffic to your Spotify, Apple Music, and YouTube Music.' },
      ],
      faq: [
        { q: 'Can I generate genre-specific content?', a: 'Yes, specify your genre — pop, rock, rap, electronic, classical — and AI matches the tone.' },
        { q: 'Can it write song lyrics?', a: 'ViralSpark generates social media content. Different tools are recommended for songwriting.' },
        { q: 'Can I include ticket links?', a: 'Absolutely. AI adds ticket sale CTAs and link directions to captions.' },
        { q: 'Is it suitable for independent artists?', a: 'Absolutely. The most affordable professional content tool for indie musicians.' },
      ],
      cta: 'Generate free content for your music career',
    },
  },
  {
    slug: 'teknoloji-startup',
    keyword: 'teknoloji startup sosyal medya',
    keywordEn: 'tech startup social media',
    icon: '🚀',
    tr: {
      h1: 'Teknoloji & Startup\'lar İçin AI İçerik Üretici',
      subtitle: 'Ürün lansmanlarından yatırımcı ilişkilerine — startup\'ınızın hikayesini AI ile anlatın.',
      intro: 'Startup dünyasında görünürlük hayatta kalma meselesi. ViralSpark, ürün tanıtımları, özellik duyuruları, ekip hikayeleri, sektör analizi içerikleri üretir — teknik derinlik ve pazarlama etkisi bir arada.',
      benefits: [
        { title: 'Ürün Hikayesi', desc: 'Teknik ürünlerinizi kullanıcı faydalarına çeviren anlatılar.' },
        { title: 'Özellik Duyuruları', desc: 'Yeni özellik, güncelleme, versiyon çıkışları için changelog postları.' },
        { title: 'Thought Leadership', desc: 'Sektör trendleri, tahminler, analiz içerikleriyle otorite kurun.' },
        { title: 'Topluluk Yönetimi', desc: 'Kullanıcı geri bildirimleri, AMA serileri, milestone kutlamaları.' },
      ],
      useCases: [
        { title: 'Product Hunt Lansmanı', desc: 'Product Hunt ve diğer platformlar için lansman içeriği hazırlayın.' },
        { title: 'Haftalık Güncelleme', desc: 'Kullanıcılarınıza haftalık gelişmeleri paylaşan update thread\'leri.' },
        { title: 'Yatırımcı İletişimi', desc: 'Metrik paylaşımları, büyüme hikayeleri, vizyon postları.' },
        { title: 'İşe Alım', desc: 'Açık pozisyonlarınızı duyuran, kültürünüzü anlatan içerikler.' },
      ],
      faq: [
        { q: 'Teknik ürünler için anlaşılır içerik üretebilir mi?', a: 'Evet, AI teknik kavramları kullanıcı faydalarına çeviren pazarlama dili kullanır.' },
        { q: 'Twitter/X thread oluşturabilir miyim?', a: 'Evet, thread aracıyla startup hikayenizi, ürün yolculuğunuzu tweet serisi olarak anlatabilirsiniz.' },
        { q: 'B2B startup için de uygun mu?', a: 'Kesinlikle. B2B, B2C, SaaS, marketplace — tüm iş modelleri için uygun.' },
        { q: 'LinkedIn içerikleri de üretebilir miyim?', a: 'Evet, LinkedIn B2B startup\'lar için en güçlü platform. ViralSpark LinkedIn postları da üretir.' },
      ],
      cta: 'Startup\'ınız için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Tech Startups',
      subtitle: 'From product launches to investor relations — tell your startup\'s story with AI.',
      intro: 'In the startup world, visibility is survival. ViralSpark generates product showcases, feature announcements, team stories, and industry analysis — combining technical depth with marketing impact.',
      benefits: [
        { title: 'Product Storytelling', desc: 'Narratives that translate technical products into user benefits.' },
        { title: 'Feature Announcements', desc: 'Changelog posts for new features, updates, and version releases.' },
        { title: 'Thought Leadership', desc: 'Build authority with industry trends, predictions, and analysis content.' },
        { title: 'Community Management', desc: 'User feedback, AMA series, and milestone celebrations.' },
      ],
      useCases: [
        { title: 'Product Hunt Launch', desc: 'Prepare launch content for Product Hunt and other platforms.' },
        { title: 'Weekly Updates', desc: 'Update threads sharing weekly developments with your users.' },
        { title: 'Investor Communication', desc: 'Metric sharing, growth stories, and vision posts.' },
        { title: 'Hiring', desc: 'Content announcing open positions and showcasing your culture.' },
      ],
      faq: [
        { q: 'Can it create understandable content for technical products?', a: 'Yes, AI uses marketing language that translates technical concepts into user benefits.' },
        { q: 'Can I create Twitter/X threads?', a: 'Yes, use the thread tool to share your startup journey as tweet series.' },
        { q: 'Is it suitable for B2B startups?', a: 'Absolutely. B2B, B2C, SaaS, marketplace — suitable for all business models.' },
        { q: 'Can I generate LinkedIn content?', a: 'Yes, LinkedIn is the strongest platform for B2B startups. ViralSpark generates LinkedIn posts.' },
      ],
      cta: 'Generate free content for your startup',
    },
  },
  {
    slug: 'moda-giyim',
    keyword: 'moda giyim markası sosyal medya',
    keywordEn: 'fashion clothing brand social media',
    icon: '👗',
    tr: {
      h1: 'Moda & Giyim Markaları İçin AI İçerik Üretici',
      subtitle: 'Koleksiyon tanıtımlarından stil önerilerine — moda markanızın sosyal medyasını AI ile şekillendirin.',
      intro: 'Moda sektörü trendlerin hızla değiştiği, sürekli fresh içerik gerektiren bir alan. ViralSpark, koleksiyon tanıtımları, stil önerileri, trend analizleri ve kampanya duyuruları için moda diline hakim içerikler üretir.',
      benefits: [
        { title: 'Trend Dili', desc: 'Moda terminolojisine hakim, sezonun renklerini ve trendlerini bilen içerikler.' },
        { title: 'Koleksiyon Tanıtımı', desc: 'Yeni sezon koleksiyonlarınızı heyecan verici şekilde tanıtın.' },
        { title: 'Stil Önerileri', desc: 'Kombin önerileri, kapsül gardırop, trend uyarlamaları — değer katan içerikler.' },
        { title: 'Satış Odaklı', desc: 'Her içerikte ürün linki, fiyat ve CTA — doğrudan satışa yönlendiren postlar.' },
      ],
      useCases: [
        { title: 'Yeni Sezon Lansmanı', desc: 'İlkbahar/yaz ve sonbahar/kış koleksiyonlarını lansmanla tanıtın.' },
        { title: 'Outfit of the Day', desc: 'Günün kombini serisiyle günlük etkileşimi artırın.' },
        { title: 'İndirim Kampanyası', desc: 'Sezon sonu, flash sale, özel gün indirimleri için aciliyet içerikleri.' },
        { title: 'Backstage/Making Of', desc: 'Tasarım sürecini, üretimi ve ilham kaynaklarını paylaşın.' },
      ],
      faq: [
        { q: 'Moda terimleri doğru kullanılıyor mu?', a: 'Evet, AI moda terminolojisine hakimdir — silüet, drapaj, avant-garde gibi terimleri doğru kullanır.' },
        { q: 'Instagram Shopping ile uyumlu mu?', a: 'AI ürün tanıtım caption\'ları üretir. Shopping etiketlerini Instagram üzerinden eklersiniz.' },
        { q: 'Lüks ve fast fashion için ayrı ton var mı?', a: 'Evet, marka profilinizde konumlandırmanızı belirtin ve AI uygun tonu kullanır.' },
        { q: 'Influencer iş birliği içerikleri üretebilir miyim?', a: 'Evet, influencer adı ve ürün detaylarını girin, AI iş birliği postu üretsin.' },
      ],
      cta: 'Moda markanız için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Fashion & Clothing Brands',
      subtitle: 'From collection launches to style tips — shape your fashion brand\'s social media with AI.',
      intro: 'Fashion is fast-moving, constantly demanding fresh content. ViralSpark generates collection showcases, style tips, trend analyses, and campaign announcements fluent in fashion language.',
      benefits: [
        { title: 'Fashion Language', desc: 'Content fluent in fashion terminology, aware of seasonal colors and trends.' },
        { title: 'Collection Launches', desc: 'Introduce new season collections with excitement and buzz.' },
        { title: 'Style Tips', desc: 'Outfit ideas, capsule wardrobes, trend adaptations — value-adding content.' },
        { title: 'Sales-Driven', desc: 'Product links, pricing, and CTAs in every post — content that drives direct sales.' },
      ],
      useCases: [
        { title: 'New Season Launch', desc: 'Launch spring/summer and fall/winter collections with impact.' },
        { title: 'Outfit of the Day', desc: 'Boost daily engagement with an OOTD series.' },
        { title: 'Sale Campaigns', desc: 'End-of-season, flash sale, and special occasion discount urgency content.' },
        { title: 'Behind the Scenes', desc: 'Share the design process, production, and inspiration sources.' },
      ],
      faq: [
        { q: 'Does it use fashion terms correctly?', a: 'Yes, AI is fluent in fashion terminology — silhouette, draping, avant-garde, and more.' },
        { q: 'Is it compatible with Instagram Shopping?', a: 'AI generates product showcase captions. Add Shopping tags through Instagram.' },
        { q: 'Are there different tones for luxury vs. fast fashion?', a: 'Yes, specify your positioning in your brand profile and AI adapts the tone.' },
        { q: 'Can I generate influencer collab content?', a: 'Yes, enter influencer names and product details for collaboration posts.' },
      ],
      cta: 'Generate free content for your fashion brand',
    },
  },
  {
    slug: 'yemek-food-blogger',
    keyword: 'yemek blogu food blogger sosyal medya',
    keywordEn: 'food blog food blogger social media',
    icon: '🍳',
    tr: {
      h1: 'Yemek Bloggerları & Food Content Creator İçin AI Asistanı',
      subtitle: 'Tariflerden restoran incelemelerine — yemek içeriklerinizi AI ile zenginleştirin.',
      intro: 'Yemek fotoğrafları çekiyorsunuz, tarifler geliştiriyorsunuz ama caption yazmak saatler alıyor. ViralSpark, tarif tanıtımları, restoran incelemeleri, besin değeri bilgileri ve food trend içerikleri üretir.',
      benefits: [
        { title: 'Tarif Tanıtımı', desc: 'Tarif adından caption, malzeme listesi özeti ve pişirme ipucu içeriği üretin.' },
        { title: 'Restoran İncelemesi', desc: 'Restoran deneyimlerinizi profesyonel inceleme formatında paylaşın.' },
        { title: 'Besin Bilgisi', desc: 'Kalori, makro değerler, diyet uygunluğu bilgileri içeren eğitici içerikler.' },
        { title: 'Viral Format', desc: 'TikTok tarif videoları, Instagram carousel tarifler için format odaklı caption\'lar.' },
      ],
      useCases: [
        { title: 'Günün Tarifi', desc: 'Her gün farklı bir tarif tanıtımıyla takipçi etkileşimini artırın.' },
        { title: 'Restoran Keşfi', desc: 'Yeni keşfettiğiniz restoranları tanıtan içerikler.' },
        { title: 'Diyet Önerileri', desc: 'Vegan, glutensiz, keto gibi diyet odaklı tarif önerileri.' },
        { title: 'Mevsimsel İçerik', desc: 'Yaz meyveleri, kış çorbaları — mevsimsel yemek içerikleri.' },
      ],
      faq: [
        { q: 'Tarif yazmak için de kullanabilir miyim?', a: 'AI sosyal medya caption\'ı üretir. Tarif detaylarını girin, AI çekici bir tanıtım metni oluştursun.' },
        { q: 'Restoran incelemesi yazabilir mi?', a: 'Evet, restoran adı, yemekler ve deneyiminizi girin, AI profesyonel inceleme formatında caption üretsin.' },
        { q: 'Türk mutfağı terminolojisi biliyor mu?', a: 'Evet — mantı, lahmacun, künefe, pide gibi tüm Türk mutfağı terimlerini doğru kullanır.' },
        { q: 'Video tarif tanıtımı da üretebilir mi?', a: 'Evet, TikTok ve Reels video açıklamaları da üretilir.' },
      ],
      cta: 'Yemek içerikleriniz için ücretsiz başlayın',
    },
    en: {
      h1: 'AI Assistant for Food Bloggers & Content Creators',
      subtitle: 'From recipes to restaurant reviews — enrich your food content with AI.',
      intro: 'You take food photos, develop recipes, but writing captions takes hours. ViralSpark generates recipe introductions, restaurant reviews, nutrition info, and food trend content.',
      benefits: [
        { title: 'Recipe Showcases', desc: 'Generate captions, ingredient summaries, and cooking tips from recipe names.' },
        { title: 'Restaurant Reviews', desc: 'Share dining experiences in professional review formats.' },
        { title: 'Nutrition Info', desc: 'Educational content with calories, macros, and dietary compatibility.' },
        { title: 'Viral Formats', desc: 'Format-focused captions for TikTok recipe videos and Instagram carousel recipes.' },
      ],
      useCases: [
        { title: 'Recipe of the Day', desc: 'Boost follower engagement with a daily recipe introduction.' },
        { title: 'Restaurant Discoveries', desc: 'Content showcasing newly discovered restaurants.' },
        { title: 'Diet-Focused Recipes', desc: 'Vegan, gluten-free, keto diet-focused recipe suggestions.' },
        { title: 'Seasonal Content', desc: 'Summer fruits, winter soups — seasonal food content.' },
      ],
      faq: [
        { q: 'Can I use it for writing recipes?', a: 'AI generates social media captions. Enter recipe details and AI creates an attractive promo text.' },
        { q: 'Can it write restaurant reviews?', a: 'Yes, enter the restaurant name, dishes, and your experience for a professional review caption.' },
        { q: 'Does it know food terminology?', a: 'Yes — cuisine-specific terms across multiple food cultures are used correctly.' },
        { q: 'Can it generate video recipe descriptions?', a: 'Yes, TikTok and Reels video descriptions are also generated.' },
      ],
      cta: 'Start free for your food content',
    },
  },
  {
    slug: 'podcast-youtube',
    keyword: 'podcast youtube içerik üretici',
    keywordEn: 'podcast youtube content creator tool',
    icon: '🎙️',
    tr: {
      h1: 'Podcast & YouTube İçerik Üreticileri İçin AI Asistanı',
      subtitle: 'Bölüm tanıtımlarından topluluk yönetimine — içerik üretim sürecinizi AI ile hızlandırın.',
      intro: 'Video çekmek veya podcast kaydetmek zamanınızın çoğunu alıyor — geriye sosyal medya için vakit kalmıyor. ViralSpark, bölüm tanıtımları, teaser metinleri, topluluk postları ve cross-platform dağıtım içerikleri üretir.',
      benefits: [
        { title: 'Bölüm Tanıtımı', desc: 'Yeni bölüm çıkışında tüm platformlar için tanıtım içeriği oluşturun.' },
        { title: 'Clip Açıklamaları', desc: 'Shorts, Reels, TikTok clip\'leri için açıklama ve hashtag üretin.' },
        { title: 'Topluluk Yönetimi', desc: 'Soru-cevap, anket, tartışma başlatan etkileşim postları.' },
        { title: 'Cross-Platform', desc: 'YouTube, Spotify, Apple Podcasts, X — her platform için ayrı içerik.' },
      ],
      useCases: [
        { title: 'Yeni Bölüm Duyurusu', desc: 'Bölüm çıkışında tüm platformlarda eş zamanlı tanıtım yapın.' },
        { title: 'Highlight Clip', desc: 'En iyi anlardan clip\'ler için çekici açıklamalar.' },
        { title: 'Konuk Tanıtımı', desc: 'Podcast konuklarınızı önceden tanıtarak heyecan yaratın.' },
        { title: 'Abone Kampanyası', desc: 'Abone/takipçi hedefi kampanyaları oluşturun.' },
      ],
      faq: [
        { q: 'YouTube video açıklaması da üretebilir mi?', a: 'Evet, SEO optimize YouTube video açıklamaları ve tag önerileri üretilebilir.' },
        { q: 'Podcast show notes yazabilir mi?', a: 'AI kısa tanıtım metinleri üretir. Detaylı show notes için bölüm özetini girin.' },
        { q: 'Thumbnail metni önerebilir mi?', a: 'Evet, dikkat çekici thumbnail metin önerileri de üretilebilir.' },
        { q: 'Birden fazla show/kanal için kullanabilir miyim?', a: 'Pro planda her show için ayrı marka profili oluşturabilirsiniz.' },
      ],
      cta: 'İçerik kanalınız için ücretsiz başlayın',
    },
    en: {
      h1: 'AI Assistant for Podcast & YouTube Creators',
      subtitle: 'From episode promos to community management — speed up your content workflow with AI.',
      intro: 'Filming videos or recording podcasts takes most of your time — there\'s nothing left for social media. ViralSpark generates episode promos, teaser copy, community posts, and cross-platform distribution content.',
      benefits: [
        { title: 'Episode Promotions', desc: 'Create promotional content across all platforms when new episodes drop.' },
        { title: 'Clip Descriptions', desc: 'Generate descriptions and hashtags for Shorts, Reels, and TikTok clips.' },
        { title: 'Community Management', desc: 'Q&A, polls, and discussion-starting engagement posts.' },
        { title: 'Cross-Platform', desc: 'YouTube, Spotify, Apple Podcasts, X — separate content for each platform.' },
      ],
      useCases: [
        { title: 'New Episode Announcements', desc: 'Simultaneously promote across all platforms when episodes drop.' },
        { title: 'Highlight Clips', desc: 'Compelling descriptions for clips of the best moments.' },
        { title: 'Guest Introductions', desc: 'Build excitement by introducing podcast guests in advance.' },
        { title: 'Subscriber Campaigns', desc: 'Create subscriber/follower milestone campaigns.' },
      ],
      faq: [
        { q: 'Can it generate YouTube video descriptions?', a: 'Yes, SEO-optimized YouTube video descriptions and tag suggestions can be generated.' },
        { q: 'Can it write podcast show notes?', a: 'AI generates short promo copy. Enter episode summaries for detailed show notes.' },
        { q: 'Can it suggest thumbnail text?', a: 'Yes, attention-grabbing thumbnail text suggestions can also be generated.' },
        { q: 'Can I use it for multiple shows/channels?', a: 'On the Pro plan, create separate brand profiles for each show.' },
      ],
      cta: 'Start free for your content channel',
    },
  },
  {
    slug: 'etkinlik-organizasyon',
    keyword: 'etkinlik organizasyon sosyal medya',
    keywordEn: 'event planning social media',
    icon: '🎪',
    tr: {
      h1: 'Etkinlik & Organizasyon Şirketleri İçin AI İçerik Üretici',
      subtitle: 'Etkinlik tanıtımlarından katılımcı etkileşimine — organizasyonlarınızı AI ile duyurun.',
      intro: 'Etkinlik sektöründe zamanında ve etkili sosyal medya iletişimi bilet satışlarının anahtarı. ViralSpark, etkinlik tanıtımları, konuşmacı duyuruları, geri sayım serileri ve katılımcı etkileşim içerikleri üretir.',
      benefits: [
        { title: 'Geri Sayım Serileri', desc: 'Etkinliğe geri sayım postları ile heyecan ve aciliyet yaratın.' },
        { title: 'Konuşmacı/Sanatçı Tanıtımı', desc: 'Etkinlik programınızdaki isimleri tanıtan profesyonel postlar.' },
        { title: 'Bilet Satışı', desc: 'Early bird, son gün, VIP — bilet satışını artıran aciliyet içerikleri.' },
        { title: 'Post-Event İçerik', desc: 'Etkinlik sonrası teşekkür, highlight ve gelecek etkinlik duyurusu.' },
      ],
      useCases: [
        { title: 'Etkinlik Lansmanı', desc: 'Yeni etkinliğinizi tüm platformlarda etkili şekilde duyurun.' },
        { title: 'Program Duyurusu', desc: 'Etkinlik programı, saatleri ve lokasyonunu paylaşın.' },
        { title: 'Sponsor Tanıtımı', desc: 'Etkinlik sponsorlarınızı tanıtan profesyonel içerikler.' },
        { title: 'Canlı Paylaşım', desc: 'Etkinlik sırasında anlık paylaşımlar için hazır şablonlar.' },
      ],
      faq: [
        { q: 'Farklı etkinlik türleri için uygun mu?', a: 'Evet — konferans, konser, fuar, düğün, kurumsal etkinlik — tüm türler.' },
        { q: 'Bilet platformu linki ekleyebilir miyim?', a: 'Evet, AI caption\'a bilet platformu CTA\'sı ve yönlendirmesi ekler.' },
        { q: 'Tekrarlayan etkinlikler için seri içerik üretebilir miyim?', a: 'Evet, takvim aracıyla haftalık/aylık etkinlik serileriniz için içerik planı oluşturun.' },
        { q: 'Etkinlik sonrası içerik de üretebilir miyim?', a: 'Evet — teşekkür postları, highlight serisi, anket ve gelecek etkinlik duyurusu.' },
      ],
      cta: 'Etkinlikleriniz için ücretsiz içerik üretin',
    },
    en: {
      h1: 'AI Content Generator for Event & Planning Companies',
      subtitle: 'From event promos to attendee engagement — announce your events with AI.',
      intro: 'In the events industry, timely and effective social media communication is the key to ticket sales. ViralSpark generates event promotions, speaker announcements, countdown series, and attendee engagement content.',
      benefits: [
        { title: 'Countdown Series', desc: 'Create excitement and urgency with countdown-to-event posts.' },
        { title: 'Speaker/Artist Spotlights', desc: 'Professional posts introducing the names in your event lineup.' },
        { title: 'Ticket Sales', desc: 'Early bird, last day, VIP — urgency content that boosts ticket sales.' },
        { title: 'Post-Event Content', desc: 'Post-event thank-yous, highlights, and next event announcements.' },
      ],
      useCases: [
        { title: 'Event Launch', desc: 'Effectively announce your new event across all platforms.' },
        { title: 'Schedule Announcements', desc: 'Share event schedule, times, and location.' },
        { title: 'Sponsor Features', desc: 'Professional content introducing your event sponsors.' },
        { title: 'Live Sharing', desc: 'Ready-made templates for real-time sharing during events.' },
      ],
      faq: [
        { q: 'Is it suitable for different event types?', a: 'Yes — conferences, concerts, expos, weddings, corporate events — all types.' },
        { q: 'Can I include ticket platform links?', a: 'Yes, AI adds ticket platform CTAs and directions to captions.' },
        { q: 'Can I generate serial content for recurring events?', a: 'Yes, use the calendar tool to create content plans for weekly/monthly event series.' },
        { q: 'Can I generate post-event content too?', a: 'Yes — thank-you posts, highlight series, surveys, and next event announcements.' },
      ],
      cta: 'Generate free content for your events',
    },
  },
]
